# call with
# ansible-playbook --extra-vars "target = <target IPv4 addr>"
---
    - name: enable NTP stats collection
      become: true
      lineinfile:
         dest: /etc/ntp.conf
         backup: yes
         insertafter: "#statsdir /var/log/ntpstats/"
         line: "statsdir /var/log/ntpstats/"
    - name: comment out default (pool) servers
      become: true
      replace:
        dest: /etc/ntp.conf
        backup: yes
        regexp: '^pool [0-3].debian.pool.ntp.org iburst'
        replace: '#pool X.debian.pool.ntp.org iburst'
    - name: configure local time servers
      become: true
      lineinfile:
         dest: /etc/ntp.conf
         backup: yes
         insertafter: "#server X.debian.pool.ntp.org iburst"
         line: "{{ item.line }}"
      with_items:
         - { line: "server x.x.x.x iburst" }
         - { line: "server x.x.x.x iburst" }
         - { line: "server x:x:x:x:x:x:x:x iburst" }
    - name: Restart the daemon with new config
      become: true
      service:
         name: ntp
         state: restarted

